version: '3'
services:
  db:
    image: blacklabelops/hsqldb
    # ports:
    #   - "9001:9001"
    volumes:
      - ./hsqldb-eshop/data/:/opt/database/
    environment:
      - HSQLDB_DATABASE_ALIAS=eshop
      - HSQLDB_DATABASE_NAME=eshop
  app:
    build:
      context: ./eshop-web
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=test"
