Je zapotrebi mit nainstalovane:

- Docker
- Java (musi byt nastavena cesta JAVA_HOME + v Path musi byt cesta do adresare bin)
- Maven (musi byt v Path)

Spustit:

  build-single

Pak funguje:

- http://localhost:8080

Jak vypnout:

  CTRL + C
  docker-compose down